In [64]:
import numpy as np

def check_winner(record_moves):
    board = np.zeros([3,3])
    player1 = 1
    player2 = -1

    for i, position in enumerate(record_moves):
        if i%2 == 0:
            board[position]=player1
        else:
            board[position]=player2

    for row in board:
        if all(cell == player1 for cell in row):
            return player1
        elif all(cell == player2 for cell in row):
            return player2

    for col in range(len(board[0])):
        if all(row[col] == player1 for row in board):
            return player1
        elif all(row[col] == player2 for row in board):
            return player2
        
    if all(board[i][i] == player1 for i in range(len(board))) or \
       all(board[i][len(board) - i - 1] == player1 for i in range(len(board))):
        return player1
    elif all(board[i][i] == player2 for i in range(len(board))) or \
       all(board[i][len(board) - i - 1] == player2 for i in range(len(board))):
        return player2

    return 0

class ticTacToe():
    def __init__(self):
        self.positions = [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
        self.outcomes = []
    def make_copy_outcomes(self):
        self.copy_outcomes = self.outcomes.copy()
    def evaluation_all_outcomes(self, record_moves, move):
        if move:
            record_moves.append(move)
        winner = check_winner(record_moves)
        if winner == 0 and len(record_moves) < 9:
            for position in self.positions:
                if not(position in record_moves):
                    self.evaluation_all_outcomes(record_moves.copy() , position)    
        else:
            self.outcomes.append([record_moves, winner])
    def render(self, record_moves):
        board = np.zeros([3,3])
        for index, move in enumerate(record_moves):
            if index%2==0:
                board[move]=1
            else:
                board[move]=-1
        print(board)

    def choose_next_step(self, record_moves):
        maked_moves = []
        for outcome in self.outcomes:
            Flag = True
            for index, move in enumerate(record_moves):
                if outcome[0][index] != move: 
                    Flag = False
            if Flag:
                maked_moves.append(outcome)

        next_moves = []

        if len(record_moves)%2 == 0:
            player = 1
        else:
            player = 2

        for position in self.positions:
            if position not in record_moves:
                
                num_variable_steps = 0
                next_move = 0
                for outcome in maked_moves:
                    if len(outcome[0]) > len(record_moves) and outcome[0][len(record_moves)] == position:
                        num_variable_steps += 1
                        next_move += outcome[1]
                if num_variable_steps != 0:
                    next_move = next_move / num_variable_steps
                next_moves.append(next_move)
            else:
                if player == 1:
                    next_moves.append(-10)
                else:
                    next_moves.append(10)

        print(np.array(next_moves).reshape(3,3))
        
        if player == 1:
            print(np.argmax(np.array(next_moves).reshape(3,3)))
            return self.positions[np.argmax(np.array(next_moves))]
        else:
            print(np.argmin(np.array(next_moves).reshape(3,3)))
            return self.positions[np.argmin(np.array(next_moves))]

        

            
env = ticTacToe()

env.evaluation_all_outcomes([], None)
env.make_copy_outcomes()





In [74]:
np.array(env.positions)


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [65]:
env.choose_next_step([(1,1), (1,2), (2,1), (0,1) ])
env.render([(1,1), (1,2), (2,1), (0,1) ])



[[  0.42857143 -10.           0.61904762]
 [  0.         -10.         -10.        ]
 [  0.33333333 -10.           0.55555556]]
2
[[ 0. -1.  0.]
 [ 0.  1. -1.]
 [ 0.  1.  0.]]


AttributeError: 'ticTacToe' object has no attribute 'step'

AttributeError: 'ticTacToe' object has no attribute 'exodus'